### ISSUE TITLE
Create Obfuscator struct

### ISSUE THREAD

**Issue by rentziass** [rentziass/misty#2]
Instead of having just the `Obfuscate` func, it would be nice it was a method of an `Obfuscator`, changing it to 
```golang
type Obfuscator struct {
  Targets []*Target
  Logger Logger
}
func (o *Obfuscator) Run (r io.Reader, writer io.Writer) error
```

That would allow us to also get rid of `Log` package level variable, which is a bad bad pattern.

**Comment by m1ome** [comment]
I am on it, if you don't mind
