### ISSUE TITLE
Refactoring of package [proposal]

### ISSUE THREAD

**Issue by m1ome** [rentziass/misty#4]
Currently package looks kinda messy.
It will be nice to refactor it:

- Add support of go.mod
- Move obfuscate rulesets into proper functions
- Adopt some logger in e.g. Logrus can be pretty handy here (or plain `log`)

**Comment by rentziass** [comment]
I won't argue with any of the above, this whole thing was put together in a rush out of necessity, but since I think it has some potential it's definitely worth some love in that sense. Do you wish to pick this up?

**Comment by m1ome** [comment]
Ofc let me try to split this up with a different issues. I will close this one when issues will be created

**Comment by m1ome** [comment]
Close this one and created separate issue for each of list item.
